openai:
  apiKey: $OPENAI_API_KEY
  model: gpt-3.5-turbo
  temperature: 0.1
  debug: true

database:
    host: 192.168.1.3
    port: 5543
    username: eshop
    password: MixdCJSf2P8Re1GS
    database: eshop